In [ ]:
# Import MindSpore.
import mindspore
# The cell outputs multiple lines at the same time.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
from mindspore import Tensor
from mindspore import dtype
# Use an array to create a tensor.
x = Tensor(10, dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

x = Tensor(np.array([1,2,3,4,5]), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

x = Tensor(np.array([[1,2,3],[4,5,6],[7,8,9]]), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

x = Tensor(np.array([0.1,0.2,0.3]), dtype.float32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")


x : 10 shape is () dimension is <bound method PyCapsule.dim of Tensor(shape=[], dtype=Int32, value= 10)>

x : [1 2 3 4 5] shape is (5,) dimension is <bound method PyCapsule.dim of Tensor(shape=[5], dtype=Int32, value= [1, 2, 3, 4, 5])>

x : [[1 2 3]
 [4 5 6]
 [7 8 9]] shape is (3, 3) dimension is <bound method PyCapsule.dim of Tensor(shape=[3, 3], dtype=Int32, value=
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])>

x : [0.1 0.2 0.3] shape is (3,) dimension is <bound method PyCapsule.data_sync of Tensor(shape=[3], dtype=Float32, value= [ 1.00000001e-01,  2.00000003e-01,  3.00000012e-01])>



In [ ]:
# Import MindSpore.
import mindspore
# The cell outputs multiple lines at the same time.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
from mindspore import Tensor
from mindspore import dtype
# Use an array to create a tensor.
x = Tensor(10, dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

x = Tensor(np.array([1,2,3,4,5]), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

x = Tensor(np.array([[1,2,3],[4,5,6],[7,8,9]]), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

x = Tensor(np.array([0,0.2,0.3]), dtype.bool_)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")


x : 10 shape is () dimension is <bound method PyCapsule.dim of Tensor(shape=[], dtype=Int32, value= 10)>

x : [1 2 3 4 5] shape is (5,) dimension is <bound method PyCapsule.dim of Tensor(shape=[5], dtype=Int32, value= [1, 2, 3, 4, 5])>

x : [[1 2 3]
 [4 5 6]
 [7 8 9]] shape is (3, 3) dimension is <bound method PyCapsule.dim of Tensor(shape=[3, 3], dtype=Int32, value=
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])>

x : [False  True  True] shape is (3,) dimension is <bound method PyCapsule.dim of Tensor(shape=[3], dtype=Bool, value= [False,  True,  True])>



In [ ]:
# Import MindSpore.
import mindspore
# The cell outputs multiple lines at the same time.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
from mindspore import Tensor
from mindspore import dtype
# Use an array to create a tensor.
x = Tensor(np.array([1,2,3]), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

y = Tensor(np.array([4,5,6]), dtype.int32)
print(f"x : {y} shape is {y.shape} dimension is {y.dim}\n")

print(f"Addition : {x+y}")
print(f"Subtraction : {x-y}")
print(f"Multiplication : {x*y}")
print(f"Division : {x/y}")

x : [1 2 3] shape is (3,) dimension is <bound method PyCapsule.dim of Tensor(shape=[3], dtype=Int32, value= [1, 2, 3])>

x : [4 5 6] shape is (3,) dimension is <bound method PyCapsule.dim of Tensor(shape=[3], dtype=Int32, value= [4, 5, 6])>

Addition : [5 7 9]
Subtraction : [-3 -3 -3]
Multiplication : [ 4 10 18]
Division : [0.25 0.4  0.5 ]


In [ ]:
# Import MindSpore.
import mindspore
# The cell outputs multiple lines at the same time.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
from mindspore import Tensor
from mindspore import dtype
# Use an array to create a tensor.
x = Tensor(np.array([[0,1],[2,3]]), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.ndim}\n")

print(f"Sum : {x.sum()}")
print(f"Mean : {x.mean()}")
print(f"Maximum : {x.max()}")
print(f"Minimum : {x.min()}")

x : [[0 1]
 [2 3]] shape is (2, 2) dimension is 2

Sum : 6
Mean : 1
Maximum : 3
Minimum : 0


In [ ]:
# Import MindSpore.
import mindspore
# The cell outputs multiple lines at the same time.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
from mindspore import Tensor
from mindspore import dtype
# Use an array to create a tensor.
x = Tensor(np.array([1,2,3]), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

y = Tensor(np.array([[10,20,30],[40,50,60]]), dtype.int32)
print(f"x : {y} shape is {y.shape} dimension is {y.dim}\n")

print(f"Addition : \n{x+y}\n")
print(f"Subtraction : \n{x-y}\n")
print(f"Multiplication : \n{x*y}\n")
print(f"Division : \n{x/y}\n")

x : [1 2 3] shape is (3,) dimension is <bound method PyCapsule.dim of Tensor(shape=[3], dtype=Int32, value= [1, 2, 3])>

x : [[10 20 30]
 [40 50 60]] shape is (2, 3) dimension is <bound method PyCapsule.dim of Tensor(shape=[2, 3], dtype=Int32, value=
[[10, 20, 30],
 [40, 50, 60]])>

Addition : 
[[11 22 33]
 [41 52 63]]

Subtraction : 
[[ -9 -18 -27]
 [-39 -48 -57]]

Multiplication : 
[[ 10  40  90]
 [ 40 100 180]]

Division : 
[[0.1   0.1   0.1  ]
 [0.025 0.04  0.05 ]]



In [ ]:
import mindspore
# The cell outputs multiple lines at the same time.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
from mindspore import Tensor
from mindspore import dtype
# Use an array to create a tensor.
x = Tensor(np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]] ), dtype.int32)
print(f"x : {x} shape is {x.shape} dimension is {x.dim}\n")

print("First Row: {}".format(x[1]))
print("Last Column: {}".format(x[:,-1]))
print("(2,1) Column: {}".format(x[2,1]))


x : [[10 20 30]
 [40 50 60]
 [70 80 90]] shape is (3, 3) dimension is <bound method PyCapsule.dim of Tensor(shape=[3, 3], dtype=Int32, value=
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])>

First Row: [40 50 60]
Last Column: [30 60 90]
(2,1) Column: 80


In [ ]:
from mindspore.ops import operations as ops
from mindspore import Tensor, dtype, ops
shape = (2, 2)
ones = ops.Zeros()
output = ones((3,3),dtype.float32)
print(output)
zeros = ops.Ones()
output = zeros((4,2), dtype.float32)
print(output)

output = ops.fill(dtype.int32, (2, 2), 7)
print(output)

output = ops.Tensor(np.random.rand(5,5),dtype.float32)
print(output)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.6630641  0.9021325  0.29700252 0.12216655 0.65850365]
 [0.20021254 0.51409215 0.02414938 0.23723961 0.9100455 ]
 [0.3302158  0.8421488  0.9599502  0.3870872  0.08069854]
 [0.94236016 0.25097018 0.521451   0.31995815 0.40406215]
 [0.49152374 0.87496996 0.22944373 0.19141199 0.6148443 ]]
